### ISSUE TITLE
Updating PSP

### ISSUE THREAD

**Issue by vsubram95** [sysdiglabs/charts#1309]
Hey Team, 

We are planning to upgrade our k8s version and we got an alert regarding the PSP policy used by the `kspm-collector`. Would it be possible to update the PSP(Pod Security Policy) in the template to automatically enable PSA(Pod Security Admission) to the namespace, because since k8s upgrade to 1.25 PSP will be depreciated.
Ref: https://github.com/sysdiglabs/charts/blob/master/charts/kspm-collector/templates/psp.yaml#L2C1-L3C1
https://kubernetes.io/docs/reference/using-api/deprecation-guide/

If its already available. Can you guide me on the update?

Cheers,
Vikranth

**Comment by mavimo** [comment]
Hi @vsubram95 

At the moment we suggest applying the PSA to the namespace you are using, we add a note to the `sysdig-deploy` chart as you can see [here](https://github.com/sysdiglabs/charts/pull/1177/files), let us know if this is not clear enough!

NB: PSP should not be automatically included when you install the chart in k8s > 1.25, but please be aware that if you are upgrading the cluster from a previous version to a version that does not support PSP, you should remove PSP before the migration (and this also in the helm release metadata); for this reason our suggestion is to have a helm release that disables PSP before the cluster upgrade, or to uninstall and reinstall the chart after the upgrade.

**Comment by vsubram95** [comment]
Thanks @mavimo. This is useful.

**Comment by anapsix** [comment]
for those getting stuck upgrading or uninstalling `sysdig-deploy` Helm chart after upgrading to K8s v1.25+ while failing to cleanup the PodSecurityPolicy objects..

1. get original version of the latest Helm chart release metadata
```
kubectl  \
  -n sysdig-agent \
  get secret sh.helm.release.v1.sysdig-agent.v10 \
  -o yaml > sh.helm.release.v1.sysdig-agent.v10.yaml
```

2. decode the "release" data
```
oq \
  -i yaml \
  -r '.data.release' \
  sh.helm.release.v1.sysdig-agent.v10.yaml \
  | base64 -D \
  | base64 -D \
  | gzip -d \
  | jq . > data_release_decoded.json
```

3. make new fixed file
```
cp \
  sh.helm.release.v1.sysdig-agent.v10.yaml \
  sh.helm.release.v1.sysdig-agent.v10_fixed.yaml
```

4. make changes in `data_release_decoded.json`, removing manifests for missing PodSecurityPolicy API objects, then re-encode it and update the `manifest` key in the "fixed" file with new data; where new data is the output of the following command
```
gzip -c data_release_decoded.json | base64 | base64
```

5. check the diff
```
diff \
  <( \
  oq \
    -i yaml \
    -r .data.release sh.helm.release.v1.sysdig-agent.v10.yaml \
    | base64 -D \
    | base64 -D \
    | gzip -d \
    | jq .manifest \
    | yq -r .) \
  <( \
  oq \
    -i yaml \
    -r .data.release sh.helm.release.v1.sysdig-agent.v10_fixed.yaml \
    | base64 -D \
    | base64 -D \
    | gzip -d \
    | jq .manifest \
    | yq -r .)
```

6. apply the changes
```
kubectl \
  -n sysdig-agent \
  apply \
  -f sh.helm.release.v1.sysdig-agent.v10_fixed.yaml
```

At this point, `helm upgrade ...` and `helm uninstall` will work, though uninstall is not needed, since we can upgrade in place
